/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_aliases.h"
#include "LED.h"
#include "LEDDuration.h"
#include "LabVIEW_UART.h"
#include "UARTReset.h"
#include "ByteReceived.h"
#include "ByteCounter.h"
#include "Clock_1.h"
#include "ByteCountReset.h"
#include "CommandReceived.h"
#include "note_clock.h"
#include "NoteInterrupt.h"
#include "NoteTimer.h"
#include "LED_Duration_Clock.h"
#include "LEDPWM.h"
#include "LED_PWM_Clock.h"
#include "LEDOffInterrupt.h"
#include "LabVIEW_UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

